<revisionlist>
  <revision rev="1" vrev="1">
    <srcmd5>89cc69c26e8627286900855b1b5c5c5f</srcmd5>
    <version>1.2</version>
    <time>1559375086</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>703205</requestid>
  </revision>
  <revision rev="2" vrev="1">
    <srcmd5>24d2c65c93f8a5baeff635c17ea35bdc</srcmd5>
    <version>1.3</version>
    <time>1560800089</time>
    <user>dimstar_suse</user>
    <comment>- Update to 1.3:
  * Fixed a bug in the tmpfs.py and passthroughfs.py example file systems</comment>
    <requestid>710356</requestid>
  </revision>
  <revision rev="3" vrev="1">
    <srcmd5>a79c9f011bc6fe4dac13c416ecc4b8d7</srcmd5>
    <version>1.3.1</version>
    <time>1563914265</time>
    <user>dimstar_suse</user>
    <comment>- Update to 1.3.1:
  *  Fixed a bug in the :file:`hello_asyncio.py` example.</comment>
    <requestid>717803</requestid>
  </revision>
  <revision rev="4" vrev="1">
    <srcmd5>2f24f37ab252f818e6a20fc4fd02abd2</srcmd5>
    <version>2.0.0</version>
    <time>1570701213</time>
    <user>dimstar_suse</user>
    <comment>- Update to 2.0.0:
  * Changed open handler to return the new FileInfo struct to allow
    for modification of certain kernel file attributes, e.g. direct_io.</comment>
    <requestid>736804</requestid>
  </revision>
  <revision rev="5" vrev="1">
    <srcmd5>5aa2a53938d8dad7cc938fe841c8eeb4</srcmd5>
    <version>3.0.0</version>
    <time>1597403442</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>824896</requestid>
  </revision>
  <revision rev="6" vrev="2">
    <srcmd5>d33d1a4ae1106d175997b6814867cf69</srcmd5>
    <version>3.0.0</version>
    <time>1615905948</time>
    <user>RBrownSUSE</user>
    <comment>- Add fix_catch_log_handler.patch to make tests compatible with
  pytest &gt;= 6.0.0, which removed never documented attribute
  .catch_log_handler of log item (gh#libfuse/pyfuse3#27).
</comment>
    <requestid>879272</requestid>
  </revision>
</revisionlist>
